spring:
  datasource:
    url: jdbc:postgresql://192.168.0.2:5432/db_sigea # ${SPRING_DATASOURCE_URL}
    username: admin #${SPRING_DATASOURCE_USERNAME}
    password: admin #${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update #temporal
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    root: WARN
    com.institucion.sigea: INFO